// Lore content for each XYZTHIAN
export const XYZTHIAN_LORE = {
  X: {
    title: 'Xaeron',
    subtitle: 'The Duality of Consciousness',
    color: '#fff',
    artifact: 'A torn newspaper clipping, yellowed with age, with cryptic headlines and a faint typewriter sound.',
    lore: `Xaeron was born from the collective outcry of extreme emotion during the Civil War. The father of the Xyzthians, he split himself to form the rest. His domain is the origin, awakening, and expansion of consciousness.`,
    principle: 'The Imperative of Unfolding Being',
    keywords: 'Origin, Awakening, Expansion, Awareness',
  },
  Y: {
    title: 'Ytaeron',
    subtitle: 'The Duality of Peace',
    color: '#ffe066',
    artifact: 'A sensory patch—hover to feel a soft breeze, a faint scent of earth, and a gentle warmth.',
    lore: `Ytaeron was created by Xaeron to handle the overwhelming need for balance and calm. Appearing in dreams as familiar things, Ytaeron guides those seeking peace.`,
    principle: 'The Mandate of Perfect Equilibrium',
    keywords: 'Harmony, Tranquility, Inner Calm',
  },
  Z: {
    title: 'Zotrexons',
    subtitle: 'The Duality of Potential',
    color: '#b0b3b8',
    artifact: 'A shifting, silvery coin that never looks the same twice.',
    lore: `Zotrexons embodies infinite possibility and the realization of all latent forms. Their domain is the flow and manifestation of potential.`,
    principle: 'The Call of the Unbound',
    keywords: 'Flow, Manifestation, Purpose, Fulfillment',
  },
  T: {
    title: 'Tenebraeum',
    subtitle: 'The Revelations',
    color: '#000',
    artifact: 'A page with shifting black ink, set on a faded map of Earth.',
    lore: `Tenebraeum brings forth hidden truths and profound insights, exposing what lies beneath the surface.`,
    principle: 'The Unveiling Imperative',
    keywords: 'Truth, Insight, Guidance, Discernment',
  },
  H: {
    title: 'Helixotopes',
    subtitle: 'The Duality of Dimensions',
    color: 'linear-gradient(90deg,#aaa,#ffd700,#aaa)',
    artifact: 'A metallic, ever-shifting spiral.',
    lore: `Helixotopes are dimensional abstract beings, endlessly exploring and bridging the layers of existence.`,
    principle: 'The Eternal Traverse',
    keywords: 'Connection, Oneness, Interconnectedness, Bridging',
  },
  I: {
    title: 'Iantheos',
    subtitle: 'The Duality of Devotion',
    color: '#cfaaff',
    artifact: 'A purple shadow that flickers and reforms.',
    lore: `Iantheos embodies the balance of control and freedom, testing the boundaries of will and commitment.`,
    principle: 'The Absolute Imperative of Will',
    keywords: 'Control, Freedom, Willpower, Commitment',
  },
  A: {
    title: 'Alithianos',
    subtitle: 'The Testaments',
    color: '#3fa9f5',
    artifact: 'A blue, illuminated manuscript page with shifting runes.',
    lore: `Alithianos weaves the tapestry of reality and illusion, revealing the subjective truth within shifting patterns.`,
    principle: 'The Enduring Weave of Perception',
    keywords: 'Reality, Illusion, Perception, Clarity, Suffering-Release',
  },
  N: {
    title: 'Nymslyornt',
    subtitle: 'The Duality of Mutastasis',
    color: 'linear-gradient(90deg,#ff0,#0ff,#f0f,#fff)',
    artifact: 'A vibrant, shifting fae charm.',
    lore: `Nymslyornt embodies spontaneous, charming, and chaotic change, disrupting fixed patterns.`,
    principle: 'The Whim of the Unpredictable',
    keywords: 'Caprice, Unpredictability, Change, Whimsy',
  },
  S: {
    title: 'Seititne',
    subtitle: 'The Veil Dwellers',
    color: '#39ff14',
    artifact: 'A neon, glowing fragment that flickers in and out of view.',
    lore: `Seititne dwell in the Veil, embodying the fragmented truth and sowing seeds of psychological distortion.`,
    principle: 'The Essence of the Fragmented Truth',
    keywords: 'Void, Misprints, Manipulation, Fragments, Imaginary, Warning',
  },
};
